apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-values-from-file
    repoUrl: https://github.com/ruanbekker/argocd-examples 
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-prod.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
